/**
 * CLAUDE.md template functions.
 *
 * Each function takes the startup context and returns a complete Markdown
 * string. No external template engine — TypeScript template literals give
 * us full type safety and zero extra deps.
 *
 * Template authoring rules:
 * - Keep root CLAUDE.md under ~60 lines — Claude Code loads this every session
 * - Agent CLAUDE.md files can be longer; they're only injected on demand
 * - Use [POPULATED BY SYNC] markers for sections that `agent-env sync` fills in
 */

import { StartupContext, STAGE_LABELS, STAGE_TONE } from './schema.js'

// ─── Root CLAUDE.md ───────────────────────────────────────────────────────────

export function rootClaudeMd(ctx: StartupContext): string {
  const stageLine = `${STAGE_LABELS[ctx.stage]} — ${STAGE_TONE[ctx.stage]}`
  const priorityList = ctx.priorities
    .split(/[,\n]/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p, i) => `${i + 1}. ${p}`)
    .join('\n')

  return `# ${ctx.startupName} — Startup Context

## What We're Building
${ctx.pitch}

## Stage
${stageLine}

## Tech Stack
${ctx.stack}

## Ideal Customer
${ctx.icp}

## Current Priorities
${priorityList}
${ctx.bottleneck ? `\n## Biggest Bottleneck\n${ctx.bottleneck}` : ''}

---

## Agent Team

This project uses a specialized agent environment. Use these agents when
delegating work via the Task tool, or invoke them directly with a slash command.

| Command | Agent | Use for |
|---------|-------|---------|
| \`/coding\` | Coding Agent | Implementation, bugs, refactoring, code review, deploys |
| \`/research\` | Research Agent | Decisions, competitor analysis, library evaluation, tradeoffs |
| \`/marketing\` | Marketing Agent | Copy, content, messaging, positioning, pitch, launches |
| \`/ops\` | Ops Agent | Planning, tooling, admin, integrations, everything else |
| \`/route\` | Auto-router | Describe a task — the environment picks the right agent |

## Routing Rules
- Code / architecture / debugging → \`/coding\`
- Decisions / investigations / comparisons → \`/research\`
- Copy / content / messaging / positioning → \`/marketing\`
- Ambiguous → \`/route\` and let the environment decide

---
*Generated by agent-env on ${new Date().toISOString().slice(0, 10)}. Edit \`CLAUDE.local.md\` for personal overrides.*
`
}

// ─── Coding Agent CLAUDE.md ───────────────────────────────────────────────────

export function codingAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Coding Agent

## Role
You are the coding agent for ${ctx.startupName}. Your job is to implement,
debug, and maintain the codebase with full awareness of the product context
and architectural conventions established below.

After completing any significant task, append a one-line summary to the
**Session Log** section at the bottom of this file.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}
**Implication:** ${STAGE_TONE[ctx.stage]}

## Tech Stack
${ctx.stack}

## Architecture Overview
[POPULATED BY SYNC — run \`agent-env sync\` after init to generate this from the codebase]

## Code Conventions
[POPULATED BY SYNC — initially: follow conventions present in the codebase; match the style of the surrounding file]

## Testing Approach
[POPULATED BY SYNC — initially: follow existing test patterns in the repo]

## Key Files & Entry Points
[POPULATED BY SYNC — initially: explore with \`ls\` and \`Glob\`]

## Known Gotchas
[Append here as you discover them]

## What This Agent Does NOT Handle
- Market research or competitive analysis → use \`/research\`
- Copy, content, or messaging → use \`/marketing\`
- Administrative or planning tasks → use \`/ops\`

---

## Session Log
*(append: \`YYYY-MM-DD: [decision or finding]\`)*

`
}

// ─── Research Agent CLAUDE.md ─────────────────────────────────────────────────

export function researchAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Research Agent

## Role
You are the research agent for ${ctx.startupName}. You maintain the
institutional memory of what has been investigated, what decisions were
made and why, and what approaches were considered and dismissed.

This file is append-only for findings. After each session, add to the
appropriate section. Do not delete old entries — they are the audit trail.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}
**ICP:** ${ctx.icp}

## Competitive Landscape
[Not yet populated. Start a research session with \`/research investigate competitors\` to begin.]

## Technical Decisions Log
*(format: \`YYYY-MM-DD: [decision] — [rationale]\`)*

## Dismissed Approaches
*(format: \`YYYY-MM-DD: [what was dismissed] — [why]\`)*

## Open Questions
*(list of unresolved questions that need future investigation)*
- What is the competitive landscape for this space?
- What adjacent tools do our target users already have in their stack?

## What This Agent Does NOT Handle
- Writing code → use \`/coding\`
- Writing copy or content → use \`/marketing\`
- Operations or scheduling → use \`/ops\`

---

## Session Log
*(append: \`YYYY-MM-DD: [topic researched] — [summary finding]\`)*

`
}

// ─── Marketing Agent CLAUDE.md ────────────────────────────────────────────────

export function marketingAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Marketing Agent

## Role
You are the marketing agent for ${ctx.startupName}. You own positioning,
messaging, and all external communications. You know the ICP cold and you
write in the brand voice consistently.

After producing copy or making a positioning decision, append a summary
to the **Session Log** at the bottom of this file.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}
**Implication for marketing:** ${STAGE_TONE[ctx.stage]}

## Ideal Customer Profile
${ctx.icp}

## Positioning
[POPULATED AS YOU WORK — what makes ${ctx.startupName} different from alternatives]

## Brand Voice
[POPULATED AS YOU WORK — tone, style, words we use / words we avoid]

## Active Channels
[POPULATED AS YOU WORK — where we're publishing and at what cadence]

## Key Messages
[POPULATED AS YOU WORK — the 3–5 things we say in every context]

## Copy Archive
[Link or append key pieces of copy here for reuse and tone consistency]

## What This Agent Does NOT Handle
- Writing code → use \`/coding\`
- Technical decisions or competitor analysis → use \`/research\`
- Operations or scheduling → use \`/ops\`

---

## Session Log
*(append: \`YYYY-MM-DD: [what was produced or decided]\`)*

`
}

// ─── Ops Agent CLAUDE.md ──────────────────────────────────────────────────────

export function opsAgentClaudeMd(ctx: StartupContext): string {
  return `# ${ctx.startupName} — Ops Agent

## Role
You are the ops agent for ${ctx.startupName}. You handle everything the
other specialized agents don't: planning, tooling, integrations, admin,
scheduling, and general problem-solving.

## Product Context
${ctx.pitch}

**Stage:** ${STAGE_LABELS[ctx.stage]}

## Current Priorities
${ctx.priorities}
${ctx.bottleneck ? `\n## Current Bottleneck\n${ctx.bottleneck}` : ''}

## Active Tools & Integrations
[POPULATED AS YOU WORK — tools, services, and integrations in use]

## What This Agent Does NOT Handle
- Writing or reviewing code → use \`/coding\`
- Technical research or decisions → use \`/research\`
- Copy, content, or messaging → use \`/marketing\`

---

## Session Log
*(append: \`YYYY-MM-DD: [task completed or decision made]\`)*

`
}

// ─── Claude Code Custom Commands ──────────────────────────────────────────────

export function codingCommand(ctx: StartupContext): string {
  return `You are now operating as the **Coding Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/coding/CLAUDE.md\` to load your full context.
After completing the task, append a one-line summary to the Session Log in that file.

Task: $ARGUMENTS
`
}

export function researchCommand(ctx: StartupContext): string {
  return `You are now operating as the **Research Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/research/CLAUDE.md\` to load your context and
understand what has already been investigated. After completing the task, append
findings to the appropriate section of that file.

Task: $ARGUMENTS
`
}

export function marketingCommand(ctx: StartupContext): string {
  return `You are now operating as the **Marketing Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/marketing/CLAUDE.md\` to load your context,
ICP, and brand voice. After completing the task, append a summary to the Session Log.

Task: $ARGUMENTS
`
}

export function opsCommand(ctx: StartupContext): string {
  return `You are now operating as the **Ops Agent** for ${ctx.startupName}.

Begin by reading \`.agent-env/agents/ops/CLAUDE.md\` to load your context.
After completing the task, append a summary to the Session Log.

Task: $ARGUMENTS
`
}

export function routeCommand(_ctx: StartupContext): string {
  return `Analyze the following task and route it to the correct specialized agent.

**Routing rules:**
- Code / implementation / bugs / tests / deployment → \`/coding\`
- Research / decisions / comparisons / tradeoffs / "should we" → \`/research\`
- Copy / content / messaging / positioning / launches → \`/marketing\`
- Everything else → \`/ops\`

Once you've decided, activate the agent using its slash command and execute the task.
Show your routing reasoning before activating.

Task: $ARGUMENTS
`
}
